### ISSUE TITLE
How to use without pushbutton?

### ISSUE THREAD

**Issue by lashanmp** [mprograms/SimpleRotary#9]
First of all, thank you for the great library. The issue is how to use it without using its pushbutton pin? The function requests 3 arguments.
![Capture](https://user-images.githubusercontent.com/59995677/117108180-738e2480-ada0-11eb-8fbd-9b9a4221ccbe.JPG)

**Comment by fyrus7** [comment]
Delete byte pinS in SimpleRotary.h

**Comment by mprograms** [comment]
> Delete byte pinS in SimpleRotary.h

It is never a good idea to edit a library directly because when an update to the library is made, it will overwrite any changes you have made and cause your code to stop working.


SimpleRotary was designed to use both rotation and push button functionality so there is no built-in function to turn this function off, however, there is a simple trick you can use to achieve your goal.

In `SimpleRotary rotary(6,5,7)` set the push button pin (pin7 in the examples) to -1. This should look like `SimpleRotary rotary(6,5,-1)`.  This is a fictitious pin and when the AVR looks up pin -1 it will not find a pin corresponding to a valid port. The AVR should read this value as 0., however, it should be noted that the AVR may end up reading the value from another memory address, so there is no way to tell what value might be returned if you tried to run any of the push button functions. But in your case, you would not care what the value would be nor would you run any push button functions so you should be ok. I have tested this on several boards and all compile and seem to run as expected.
